FROM python:3.9-slim

RUN apt-get update && apt-get install -y libpq-dev gcc && apt-get clean

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY viz.py .
COPY __init__.py .

EXPOSE 8050

CMD ["python", "viz.py"]
